version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: bd-trabalho-final
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacinacao
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
