version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Caso queira inicializar com um script SQL:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: